Manage adding items by logging module
beyond-io/givit pull request #98
Opened 2020-09-21 12:49 UTC by rotem-benzvi

Our app now handle all the added items in agora.log using django logging module.
the commit:
1. we add to settings.py logging module and 2 loggers- for agora and for requests.
2. add logs directory that include all the log files.

fixed: #62

2020-09-21 12:57 UTC, lioramilbaum requested changes
Your PR needs a rebase

2020-09-21 13:06 UTC, rotem-benzvi commented
> Your PR needs a rebase

yes sorry, i solved now the conflict.

2020-09-21 15:20 UTC, lioramilbaum reviewed
Do you have a test which validates givit_main()?

2020-09-22 06:38 UTC, rotem-benzvi commented
> Do you have a test which validates givit_main()?

not yet, i add issue for gatherer test and link it to this PR - #100

2020-09-22 08:36 UTC, lioramilbaum approved these changes
I will approve this PR as the last one which doesn't have tests. From now on, you should bake your PRs with the tests which validates the code. 
The maintainer doesn't have the knowledge/experience in the technology used. The tests which validates the changes provide confidence in the code. Does that make sense?

2020-09-22 11:34 UTC, rotem-benzvi commented
> The maintainer doesn't have the knowledge/experience in the technology used. The tests which validates the changes provide confidence in the code. Does that make sense?

yes definitely, i will do it 👍

2020-09-22 11:34 UTC, merged